from datetime import datetime
from sqlalchemy import String, Integer, Boolean, Date, DateTime, Float, ForeignKey, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column, relationship
from .database import Base
def now(): return datetime.now()
class User(Base):
    __tablename__='users'; id: Mapped[int]=mapped_column(primary_key=True); full_name: Mapped[str]=mapped_column(String(120)); username: Mapped[str]=mapped_column(String(60), unique=True, index=True); password_hash: Mapped[str]=mapped_column(String(255)); role: Mapped[str]=mapped_column(String(20)); is_active: Mapped[bool]=mapped_column(Boolean, default=True); last_login_at: Mapped[datetime|None]=mapped_column(DateTime, nullable=True); created_at: Mapped[datetime]=mapped_column(DateTime, default=now); updated_at: Mapped[datetime]=mapped_column(DateTime, default=now, onupdate=now)
class ClassRoom(Base):
    __tablename__='classes'; id: Mapped[int]=mapped_column(primary_key=True); name: Mapped[str]=mapped_column(String(80), unique=True); grade: Mapped[str]=mapped_column(String(10)); major: Mapped[str]=mapped_column(String(80)); school_year: Mapped[str]=mapped_column(String(20)); is_active: Mapped[bool]=mapped_column(Boolean,default=True); created_at: Mapped[datetime]=mapped_column(DateTime,default=now); updated_at: Mapped[datetime]=mapped_column(DateTime,default=now,onupdate=now)
class Major(Base):
    __tablename__='majors'; id: Mapped[int]=mapped_column(primary_key=True); name: Mapped[str]=mapped_column(String(120),unique=True,index=True); is_active: Mapped[bool]=mapped_column(Boolean,default=True); created_at: Mapped[datetime]=mapped_column(DateTime,default=now); updated_at: Mapped[datetime]=mapped_column(DateTime,default=now,onupdate=now)
class Guardian(Base):
    __tablename__='guardians'; id: Mapped[int]=mapped_column(primary_key=True); full_name: Mapped[str]=mapped_column(String(120)); phone_number: Mapped[str]=mapped_column(String(20)); is_active: Mapped[bool]=mapped_column(Boolean,default=True); created_at: Mapped[datetime]=mapped_column(DateTime,default=now); updated_at: Mapped[datetime]=mapped_column(DateTime,default=now,onupdate=now)
class GuardianAccount(Base):
    __tablename__='guardian_accounts'; id: Mapped[int]=mapped_column(primary_key=True); guardian_id: Mapped[int]=mapped_column(ForeignKey('guardians.id'),unique=True,index=True); user_id: Mapped[int]=mapped_column(ForeignKey('users.id'),unique=True,index=True); created_at: Mapped[datetime]=mapped_column(DateTime,default=now)
class GuardianStudent(Base):
    __tablename__='guardian_students'; __table_args__=(UniqueConstraint('guardian_id','student_id',name='uq_guardian_student'),); id: Mapped[int]=mapped_column(primary_key=True); guardian_id: Mapped[int]=mapped_column(ForeignKey('guardians.id'),index=True); student_id: Mapped[int]=mapped_column(ForeignKey('students.id'),index=True); relationship: Mapped[str]=mapped_column(String(40),default='Wali'); created_at: Mapped[datetime]=mapped_column(DateTime,default=now)
class Student(Base):
    __tablename__='students'; id: Mapped[int]=mapped_column(primary_key=True); nis: Mapped[str]=mapped_column(String(40),unique=True,index=True); full_name: Mapped[str]=mapped_column(String(120)); class_id: Mapped[int]=mapped_column(ForeignKey('classes.id')); guardian_id: Mapped[int|None]=mapped_column(ForeignKey('guardians.id'),nullable=True); gender: Mapped[str|None]=mapped_column(String(10),nullable=True); is_active: Mapped[bool]=mapped_column(Boolean,default=True); photo_path: Mapped[str|None]=mapped_column(String(255),nullable=True); face_enrollment_status: Mapped[str]=mapped_column(String(20),default='NOT_REGISTERED'); created_at: Mapped[datetime]=mapped_column(DateTime,default=now); updated_at: Mapped[datetime]=mapped_column(DateTime,default=now,onupdate=now); classroom=relationship('ClassRoom'); guardian=relationship('Guardian')
class FaceEnrollment(Base):
    __tablename__='face_enrollments'; id: Mapped[int]=mapped_column(primary_key=True); student_id: Mapped[int]=mapped_column(ForeignKey('students.id'),unique=True); embedding_path: Mapped[str|None]=mapped_column(String(255)); sample_count: Mapped[int]=mapped_column(Integer,default=0); model_name: Mapped[str]=mapped_column(String(100)); registered_by: Mapped[int]=mapped_column(ForeignKey('users.id')); registered_at: Mapped[datetime]=mapped_column(DateTime,default=now); updated_at: Mapped[datetime]=mapped_column(DateTime,default=now,onupdate=now)
class AttendanceSession(Base):
    __tablename__='attendance_sessions'; id: Mapped[int]=mapped_column(primary_key=True); session_date: Mapped[datetime]=mapped_column(DateTime,default=now); mode: Mapped[str]=mapped_column(String(20)); status: Mapped[str]=mapped_column(String(12),default='ACTIVE'); camera_source: Mapped[str]=mapped_column(String(255)); opened_by: Mapped[int]=mapped_column(ForeignKey('users.id')); opened_at: Mapped[datetime]=mapped_column(DateTime,default=now); closed_at: Mapped[datetime|None]=mapped_column(DateTime,nullable=True)
class Attendance(Base):
    __tablename__='attendance'; __table_args__=(UniqueConstraint('student_id','attendance_date',name='uq_student_day'),); id: Mapped[int]=mapped_column(primary_key=True); student_id: Mapped[int]=mapped_column(ForeignKey('students.id')); attendance_date: Mapped[Date]=mapped_column(Date); check_in_time: Mapped[datetime|None]=mapped_column(DateTime,nullable=True); check_out_time: Mapped[datetime|None]=mapped_column(DateTime,nullable=True); status: Mapped[str]=mapped_column(String(20),default='PRESENT'); check_in_method: Mapped[str|None]=mapped_column(String(12),nullable=True); check_out_method: Mapped[str|None]=mapped_column(String(12),nullable=True); confidence_score: Mapped[float|None]=mapped_column(Float,nullable=True); notes: Mapped[str|None]=mapped_column(Text,nullable=True); created_by: Mapped[int|None]=mapped_column(ForeignKey('users.id'),nullable=True); updated_by: Mapped[int|None]=mapped_column(ForeignKey('users.id'),nullable=True); created_at: Mapped[datetime]=mapped_column(DateTime,default=now); updated_at: Mapped[datetime]=mapped_column(DateTime,default=now,onupdate=now); student=relationship('Student')
class LeaveRequest(Base):
    __tablename__='leave_requests'; id: Mapped[int]=mapped_column(primary_key=True); student_id: Mapped[int]=mapped_column(ForeignKey('students.id')); leave_date: Mapped[Date]=mapped_column(Date); leave_type: Mapped[str]=mapped_column(String(20)); reason: Mapped[str]=mapped_column(Text); evidence_path: Mapped[str|None]=mapped_column(String(255),nullable=True); status: Mapped[str]=mapped_column(String(12),default='PENDING'); submitted_by: Mapped[int]=mapped_column(ForeignKey('users.id')); reviewed_by: Mapped[int|None]=mapped_column(ForeignKey('users.id'),nullable=True); review_note: Mapped[str|None]=mapped_column(Text,nullable=True); created_at: Mapped[datetime]=mapped_column(DateTime,default=now); reviewed_at: Mapped[datetime|None]=mapped_column(DateTime,nullable=True); student=relationship('Student')
class AuditLog(Base):
    __tablename__='audit_logs'; id: Mapped[int]=mapped_column(primary_key=True); user_id: Mapped[int|None]=mapped_column(ForeignKey('users.id'),nullable=True); action: Mapped[str]=mapped_column(String(80)); entity_type: Mapped[str]=mapped_column(String(80)); entity_id: Mapped[str|None]=mapped_column(String(50),nullable=True); description: Mapped[str]=mapped_column(Text); created_at: Mapped[datetime]=mapped_column(DateTime,default=now)
